create type currency_type as enum ('RUB', 'USD', 'EUR', 'GBP', 'HKD', 'CHF', 'JPY', 'CNY', 'TRY');
create type status_type as enum ('IN_PROGRESS','SUCCESS','FAILED','APPROVED');
create type payment_method_type as enum ('CARD');
create type messages_type as enum ('OK', 'PAYMENT_METHOD_NOT_ALLOWED', 'PAYMENT_IS_SUCCESS_FULLY_COMPLETED', 'PAY_OUT_MIN_AMOUNT');
create type transaction_type as enum ('TOP_UP', 'PAY_OUT');
create type languages as enum ('RU', 'DE', 'EN');
create type role_type as enum ('USER','ADMIN');
create type status_role_type as enum ('ACTIVE', 'BANNED');
create type user_type as enum ('CUSTOMER', 'MERCHANT');

CREATE TABLE customer
(
    id         bigint primary key generated by default as identity,
    first_name varchar(50) not null,
    last_name  varchar(50) not null,
    country    varchar(50) not null
);
CREATE TABLE card
(
    card_number bigint primary key generated by default as identity,
    exp_date    integer not null,
    cvv         integer not null,
    balance     bigint  not null,
    user_type   user_type,
    customer_id bigint references customer (id) on delete cascade

);
CREATE TABLE bank_account
(
    id       bigint primary key generated by default as identity,
    currency currency_type,
    balance  bigint not null,
    owner_Id bigint references customer (id) on delete cascade

);
CREATE TABLE merchant
(
    id              bigint primary key generated by default as identity,
    bank_account_id bigint references bank_account (id),
    create_at       timestamp,
    update_at       timestamp,
    response_status status_type,
    request_status  status_type,
    secret_key      varchar

);

CREATE TABLE web_hook
(
    id              bigint primary key generated by default as identity,

    create_at       timestamp,
    update_at       timestamp,
    transaction     transaction_type,
    payment_method  payment_method_type,
    message         messages_type,
    language        languages,
    url             varchar(255),
    response_status status_type,
    request_status  status_type,
    count_attempt   integer

);

CREATE TABLE transaction
(
    id                   bigint primary key generated by default as identity,
    payment_method       payment_method_type,
    transaction_type     transaction_type,
    create_at            timestamp,
    update_at            timestamp,
    response_status      status_type,
    request_status       status_type,
    from_bank_account_Id bigint references bank_account (id) on delete cascade,
    to_bank_account_Id   bigint references bank_account (id) on delete cascade,
    currency             currency_type,
    amount               bigint,
    language             languages,
    message              messages_type,
    notification_url     varchar(255),
    web_hook_id bigint references web_hook(id) on  delete cascade

);


